title: "Ari's Blog"
author: 
  name: "Ari Pratama Zhorifiandi"
  email: "zhorifiandi@gmail.com"
description: "Mostly my personal notes on Software Engineering, Startup and other stuffs. Take it with grain of salt." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "zhorifiandi@gmail.com"
twitter_username: "zhorifiandi"
github_username: "zhorifiandi"
linkedin_username: "zhorifiandi"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
# Debug here: https://github.com/jekyll/minima/blob/master/_layouts/home.html
# theme: "minima"
remote_theme: jekyll/minima

minima:
  skin: dark
  # Email / Social media user names used by the minima theme:
  # All of these are optional and can be removed or commented out
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/zhorifiandi" }
    - { platform: github, user_url: "https://github.com/zhorifiandi" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/zhorifiandi" }


show_excerpts: true
rss: rss

mermaid: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme

defaults:
  - scope:
      path: "misc"
      type: post
    values:
      tags: Misc
