title: "Ari's Blog"
author: "Ari Pratama Zhorifiandi"
description: "Mostly personal notes of Software Engineering and stuffs. Take it with grain of salt." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "zhorifiandi@gmail.com"
twitter_username: "zhorifiandi"
github_username: "zhorifiandi"
linkedin_username: "zhorifiandi"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
# Debug here: https://github.com/jekyll/minima/blob/master/_layouts/home.html
theme: "minima"

show_excerpts: true
rss: rss

mermaid: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

defaults:
  - scope:
      path: "misc"
      type: post
    values:
      tags: Misc
