name: Notion to Jekyll

on:
  schedule:
    - cron: '0 0 * * *' # Run every midnight
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # Required for GitHub action to save files

jobs:
  notion-to-jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notion to Jekyll synchronization
        uses: whatasame/notion-to-jekyll@v0 # latest version
        with:
          notion_api_key: ${{ secrets.NOTION_SECRET }}
          notion_database_id: c5e396e0ba1345faad1cacddffe1cf53